'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.8745
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("DS_cuadratura_fin_de_mes"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class DS_cuadratura_fin_de_mes
    Inherits Global.System.Data.DataSet
    
    Private tablecuadratura_fin_de_mes As cuadratura_fin_de_mesDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("cuadratura_fin_de_mes")) Is Nothing) Then
                MyBase.Tables.Add(New cuadratura_fin_de_mesDataTable(ds.Tables("cuadratura_fin_de_mes")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property cuadratura_fin_de_mes() As cuadratura_fin_de_mesDataTable
        Get
            Return Me.tablecuadratura_fin_de_mes
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As DS_cuadratura_fin_de_mes = CType(MyBase.Clone,DS_cuadratura_fin_de_mes)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("cuadratura_fin_de_mes")) Is Nothing) Then
                MyBase.Tables.Add(New cuadratura_fin_de_mesDataTable(ds.Tables("cuadratura_fin_de_mes")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tablecuadratura_fin_de_mes = CType(MyBase.Tables("cuadratura_fin_de_mes"),cuadratura_fin_de_mesDataTable)
        If (initTable = true) Then
            If (Not (Me.tablecuadratura_fin_de_mes) Is Nothing) Then
                Me.tablecuadratura_fin_de_mes.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "DS_cuadratura_fin_de_mes"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/DS_cuadratura_fin_de_mes.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tablecuadratura_fin_de_mes = New cuadratura_fin_de_mesDataTable
        MyBase.Tables.Add(Me.tablecuadratura_fin_de_mes)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerializecuadratura_fin_de_mes() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As DS_cuadratura_fin_de_mes = New DS_cuadratura_fin_de_mes
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    Public Delegate Sub cuadratura_fin_de_mesRowChangeEventHandler(ByVal sender As Object, ByVal e As cuadratura_fin_de_mesRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class cuadratura_fin_de_mesDataTable
        Inherits Global.System.Data.TypedTableBase(Of cuadratura_fin_de_mesRow)
        
        Private columnDataColumn1 As Global.System.Data.DataColumn
        
        Private columnDataColumn2 As Global.System.Data.DataColumn
        
        Private columnDataColumn3 As Global.System.Data.DataColumn
        
        Private columnDataColumn4 As Global.System.Data.DataColumn
        
        Private columnDataColumn5 As Global.System.Data.DataColumn
        
        Private columnDataColumn6 As Global.System.Data.DataColumn
        
        Private columnDataColumn7 As Global.System.Data.DataColumn
        
        Private columnDataColumn8 As Global.System.Data.DataColumn
        
        Private columnDataColumn9 As Global.System.Data.DataColumn
        
        Private columnDataColumn10 As Global.System.Data.DataColumn
        
        Private columnDataColumn11 As Global.System.Data.DataColumn
        
        Private columnDataColumn12 As Global.System.Data.DataColumn
        
        Private columnDataColumn13 As Global.System.Data.DataColumn
        
        Private columnDataColumn14 As Global.System.Data.DataColumn
        
        Private columnDataColumn15 As Global.System.Data.DataColumn
        
        Private columnDataColumn16 As Global.System.Data.DataColumn
        
        Private columnDataColumn17 As Global.System.Data.DataColumn
        
        Private columnDataColumn18 As Global.System.Data.DataColumn
        
        Private columnDataColumn19 As Global.System.Data.DataColumn
        
        Private columnDataColumn20 As Global.System.Data.DataColumn
        
        Private columnlogo As Global.System.Data.DataColumn
        
        Private columnDataColumn21 As Global.System.Data.DataColumn
        
        Private columnDataColumn22 As Global.System.Data.DataColumn
        
        Private columnDataColumn23 As Global.System.Data.DataColumn
        
        Private columnDataColumn24 As Global.System.Data.DataColumn
        
        Private columnDataColumn25 As Global.System.Data.DataColumn
        
        Private columnDataColumn26 As Global.System.Data.DataColumn
        
        Private columnDataColumn27 As Global.System.Data.DataColumn
        
        Private columnDataColumn28 As Global.System.Data.DataColumn
        
        Private columnDataColumn29 As Global.System.Data.DataColumn
        
        Private columnDataColumn30 As Global.System.Data.DataColumn
        
        Private columnDataColumn31 As Global.System.Data.DataColumn
        
        Private columnDataColumn32 As Global.System.Data.DataColumn
        
        Private columnDataColumn33 As Global.System.Data.DataColumn
        
        Private columnDataColumn34 As Global.System.Data.DataColumn
        
        Private columnDataColumn35 As Global.System.Data.DataColumn
        
        Private columnDataColumn36 As Global.System.Data.DataColumn
        
        Private columnDataColumn37 As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "cuadratura_fin_de_mes"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn1Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn1
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn2Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn2
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn3Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn3
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn4Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn4
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn5Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn5
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn6Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn6
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn7Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn7
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn8Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn8
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn9Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn9
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn10Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn10
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn11Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn11
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn12Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn12
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn13Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn13
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn14Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn14
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn15Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn15
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn16Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn16
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn17Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn17
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn18Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn18
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn19Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn19
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn20Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn20
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property logoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnlogo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn21Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn21
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn22Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn22
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn23Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn23
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn24Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn24
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn25Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn25
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn26Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn26
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn27Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn27
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn28Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn28
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn29Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn29
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn30Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn30
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn31Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn31
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn32Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn32
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn33Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn33
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn34Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn34
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn35Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn35
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn36Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn36
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DataColumn37Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDataColumn37
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As cuadratura_fin_de_mesRow
            Get
                Return CType(Me.Rows(index),cuadratura_fin_de_mesRow)
            End Get
        End Property
        
        Public Event cuadratura_fin_de_mesRowChanging As cuadratura_fin_de_mesRowChangeEventHandler
        
        Public Event cuadratura_fin_de_mesRowChanged As cuadratura_fin_de_mesRowChangeEventHandler
        
        Public Event cuadratura_fin_de_mesRowDeleting As cuadratura_fin_de_mesRowChangeEventHandler
        
        Public Event cuadratura_fin_de_mesRowDeleted As cuadratura_fin_de_mesRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub Addcuadratura_fin_de_mesRow(ByVal row As cuadratura_fin_de_mesRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function Addcuadratura_fin_de_mesRow( _
                    ByVal DataColumn1 As String,  _
                    ByVal DataColumn2 As String,  _
                    ByVal DataColumn3 As String,  _
                    ByVal DataColumn4 As String,  _
                    ByVal DataColumn5 As String,  _
                    ByVal DataColumn6 As String,  _
                    ByVal DataColumn7 As String,  _
                    ByVal DataColumn8 As String,  _
                    ByVal DataColumn9 As String,  _
                    ByVal DataColumn10 As String,  _
                    ByVal DataColumn11 As String,  _
                    ByVal DataColumn12 As String,  _
                    ByVal DataColumn13 As String,  _
                    ByVal DataColumn14 As String,  _
                    ByVal DataColumn15 As String,  _
                    ByVal DataColumn16 As String,  _
                    ByVal DataColumn17 As String,  _
                    ByVal DataColumn18 As String,  _
                    ByVal DataColumn19 As String,  _
                    ByVal DataColumn20 As String,  _
                    ByVal logo() As Byte,  _
                    ByVal DataColumn21 As String,  _
                    ByVal DataColumn22 As Integer,  _
                    ByVal DataColumn23 As Integer,  _
                    ByVal DataColumn24 As Integer,  _
                    ByVal DataColumn25 As Integer,  _
                    ByVal DataColumn26 As Integer,  _
                    ByVal DataColumn27 As Integer,  _
                    ByVal DataColumn28 As String,  _
                    ByVal DataColumn29 As String,  _
                    ByVal DataColumn30 As String,  _
                    ByVal DataColumn31 As String,  _
                    ByVal DataColumn32 As Integer,  _
                    ByVal DataColumn33 As Integer,  _
                    ByVal DataColumn34 As Integer,  _
                    ByVal DataColumn35 As String,  _
                    ByVal DataColumn36 As String,  _
                    ByVal DataColumn37 As String) As cuadratura_fin_de_mesRow
            Dim rowcuadratura_fin_de_mesRow As cuadratura_fin_de_mesRow = CType(Me.NewRow,cuadratura_fin_de_mesRow)
            Dim columnValuesArray() As Object = New Object() {DataColumn1, DataColumn2, DataColumn3, DataColumn4, DataColumn5, DataColumn6, DataColumn7, DataColumn8, DataColumn9, DataColumn10, DataColumn11, DataColumn12, DataColumn13, DataColumn14, DataColumn15, DataColumn16, DataColumn17, DataColumn18, DataColumn19, DataColumn20, logo, DataColumn21, DataColumn22, DataColumn23, DataColumn24, DataColumn25, DataColumn26, DataColumn27, DataColumn28, DataColumn29, DataColumn30, DataColumn31, DataColumn32, DataColumn33, DataColumn34, DataColumn35, DataColumn36, DataColumn37}
            rowcuadratura_fin_de_mesRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowcuadratura_fin_de_mesRow)
            Return rowcuadratura_fin_de_mesRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As cuadratura_fin_de_mesDataTable = CType(MyBase.Clone,cuadratura_fin_de_mesDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New cuadratura_fin_de_mesDataTable
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columnDataColumn1 = MyBase.Columns("DataColumn1")
            Me.columnDataColumn2 = MyBase.Columns("DataColumn2")
            Me.columnDataColumn3 = MyBase.Columns("DataColumn3")
            Me.columnDataColumn4 = MyBase.Columns("DataColumn4")
            Me.columnDataColumn5 = MyBase.Columns("DataColumn5")
            Me.columnDataColumn6 = MyBase.Columns("DataColumn6")
            Me.columnDataColumn7 = MyBase.Columns("DataColumn7")
            Me.columnDataColumn8 = MyBase.Columns("DataColumn8")
            Me.columnDataColumn9 = MyBase.Columns("DataColumn9")
            Me.columnDataColumn10 = MyBase.Columns("DataColumn10")
            Me.columnDataColumn11 = MyBase.Columns("DataColumn11")
            Me.columnDataColumn12 = MyBase.Columns("DataColumn12")
            Me.columnDataColumn13 = MyBase.Columns("DataColumn13")
            Me.columnDataColumn14 = MyBase.Columns("DataColumn14")
            Me.columnDataColumn15 = MyBase.Columns("DataColumn15")
            Me.columnDataColumn16 = MyBase.Columns("DataColumn16")
            Me.columnDataColumn17 = MyBase.Columns("DataColumn17")
            Me.columnDataColumn18 = MyBase.Columns("DataColumn18")
            Me.columnDataColumn19 = MyBase.Columns("DataColumn19")
            Me.columnDataColumn20 = MyBase.Columns("DataColumn20")
            Me.columnlogo = MyBase.Columns("logo")
            Me.columnDataColumn21 = MyBase.Columns("DataColumn21")
            Me.columnDataColumn22 = MyBase.Columns("DataColumn22")
            Me.columnDataColumn23 = MyBase.Columns("DataColumn23")
            Me.columnDataColumn24 = MyBase.Columns("DataColumn24")
            Me.columnDataColumn25 = MyBase.Columns("DataColumn25")
            Me.columnDataColumn26 = MyBase.Columns("DataColumn26")
            Me.columnDataColumn27 = MyBase.Columns("DataColumn27")
            Me.columnDataColumn28 = MyBase.Columns("DataColumn28")
            Me.columnDataColumn29 = MyBase.Columns("DataColumn29")
            Me.columnDataColumn30 = MyBase.Columns("DataColumn30")
            Me.columnDataColumn31 = MyBase.Columns("DataColumn31")
            Me.columnDataColumn32 = MyBase.Columns("DataColumn32")
            Me.columnDataColumn33 = MyBase.Columns("DataColumn33")
            Me.columnDataColumn34 = MyBase.Columns("DataColumn34")
            Me.columnDataColumn35 = MyBase.Columns("DataColumn35")
            Me.columnDataColumn36 = MyBase.Columns("DataColumn36")
            Me.columnDataColumn37 = MyBase.Columns("DataColumn37")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columnDataColumn1 = New Global.System.Data.DataColumn("DataColumn1", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn1)
            Me.columnDataColumn2 = New Global.System.Data.DataColumn("DataColumn2", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn2)
            Me.columnDataColumn3 = New Global.System.Data.DataColumn("DataColumn3", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn3)
            Me.columnDataColumn4 = New Global.System.Data.DataColumn("DataColumn4", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn4)
            Me.columnDataColumn5 = New Global.System.Data.DataColumn("DataColumn5", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn5)
            Me.columnDataColumn6 = New Global.System.Data.DataColumn("DataColumn6", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn6)
            Me.columnDataColumn7 = New Global.System.Data.DataColumn("DataColumn7", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn7)
            Me.columnDataColumn8 = New Global.System.Data.DataColumn("DataColumn8", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn8)
            Me.columnDataColumn9 = New Global.System.Data.DataColumn("DataColumn9", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn9)
            Me.columnDataColumn10 = New Global.System.Data.DataColumn("DataColumn10", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn10)
            Me.columnDataColumn11 = New Global.System.Data.DataColumn("DataColumn11", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn11)
            Me.columnDataColumn12 = New Global.System.Data.DataColumn("DataColumn12", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn12)
            Me.columnDataColumn13 = New Global.System.Data.DataColumn("DataColumn13", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn13)
            Me.columnDataColumn14 = New Global.System.Data.DataColumn("DataColumn14", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn14)
            Me.columnDataColumn15 = New Global.System.Data.DataColumn("DataColumn15", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn15)
            Me.columnDataColumn16 = New Global.System.Data.DataColumn("DataColumn16", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn16)
            Me.columnDataColumn17 = New Global.System.Data.DataColumn("DataColumn17", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn17)
            Me.columnDataColumn18 = New Global.System.Data.DataColumn("DataColumn18", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn18)
            Me.columnDataColumn19 = New Global.System.Data.DataColumn("DataColumn19", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn19)
            Me.columnDataColumn20 = New Global.System.Data.DataColumn("DataColumn20", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn20)
            Me.columnlogo = New Global.System.Data.DataColumn("logo", GetType(Byte()), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnlogo)
            Me.columnDataColumn21 = New Global.System.Data.DataColumn("DataColumn21", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn21)
            Me.columnDataColumn22 = New Global.System.Data.DataColumn("DataColumn22", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn22)
            Me.columnDataColumn23 = New Global.System.Data.DataColumn("DataColumn23", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn23)
            Me.columnDataColumn24 = New Global.System.Data.DataColumn("DataColumn24", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn24)
            Me.columnDataColumn25 = New Global.System.Data.DataColumn("DataColumn25", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn25)
            Me.columnDataColumn26 = New Global.System.Data.DataColumn("DataColumn26", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn26)
            Me.columnDataColumn27 = New Global.System.Data.DataColumn("DataColumn27", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn27)
            Me.columnDataColumn28 = New Global.System.Data.DataColumn("DataColumn28", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn28)
            Me.columnDataColumn29 = New Global.System.Data.DataColumn("DataColumn29", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn29)
            Me.columnDataColumn30 = New Global.System.Data.DataColumn("DataColumn30", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn30)
            Me.columnDataColumn31 = New Global.System.Data.DataColumn("DataColumn31", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn31)
            Me.columnDataColumn32 = New Global.System.Data.DataColumn("DataColumn32", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn32)
            Me.columnDataColumn33 = New Global.System.Data.DataColumn("DataColumn33", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn33)
            Me.columnDataColumn34 = New Global.System.Data.DataColumn("DataColumn34", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn34)
            Me.columnDataColumn35 = New Global.System.Data.DataColumn("DataColumn35", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn35)
            Me.columnDataColumn36 = New Global.System.Data.DataColumn("DataColumn36", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn36)
            Me.columnDataColumn37 = New Global.System.Data.DataColumn("DataColumn37", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDataColumn37)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Newcuadratura_fin_de_mesRow() As cuadratura_fin_de_mesRow
            Return CType(Me.NewRow,cuadratura_fin_de_mesRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New cuadratura_fin_de_mesRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(cuadratura_fin_de_mesRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.cuadratura_fin_de_mesRowChangedEvent) Is Nothing) Then
                RaiseEvent cuadratura_fin_de_mesRowChanged(Me, New cuadratura_fin_de_mesRowChangeEvent(CType(e.Row,cuadratura_fin_de_mesRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.cuadratura_fin_de_mesRowChangingEvent) Is Nothing) Then
                RaiseEvent cuadratura_fin_de_mesRowChanging(Me, New cuadratura_fin_de_mesRowChangeEvent(CType(e.Row,cuadratura_fin_de_mesRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.cuadratura_fin_de_mesRowDeletedEvent) Is Nothing) Then
                RaiseEvent cuadratura_fin_de_mesRowDeleted(Me, New cuadratura_fin_de_mesRowChangeEvent(CType(e.Row,cuadratura_fin_de_mesRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.cuadratura_fin_de_mesRowDeletingEvent) Is Nothing) Then
                RaiseEvent cuadratura_fin_de_mesRowDeleting(Me, New cuadratura_fin_de_mesRowChangeEvent(CType(e.Row,cuadratura_fin_de_mesRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Removecuadratura_fin_de_mesRow(ByVal row As cuadratura_fin_de_mesRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
            Dim ds As DS_cuadratura_fin_de_mes = New DS_cuadratura_fin_de_mes
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "cuadratura_fin_de_mesDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class cuadratura_fin_de_mesRow
        Inherits Global.System.Data.DataRow
        
        Private tablecuadratura_fin_de_mes As cuadratura_fin_de_mesDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tablecuadratura_fin_de_mes = CType(Me.Table,cuadratura_fin_de_mesDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn1() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn1Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn1' de la tabla 'cuadratura_fin_de_mes' es DBNul"& _ 
                            "l.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn1Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn2() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn2Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn2' de la tabla 'cuadratura_fin_de_mes' es DBNul"& _ 
                            "l.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn2Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn3() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn3Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn3' de la tabla 'cuadratura_fin_de_mes' es DBNul"& _ 
                            "l.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn3Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn4() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn4Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn4' de la tabla 'cuadratura_fin_de_mes' es DBNul"& _ 
                            "l.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn4Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn5() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn5Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn5' de la tabla 'cuadratura_fin_de_mes' es DBNul"& _ 
                            "l.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn5Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn6() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn6Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn6' de la tabla 'cuadratura_fin_de_mes' es DBNul"& _ 
                            "l.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn6Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn7() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn7Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn7' de la tabla 'cuadratura_fin_de_mes' es DBNul"& _ 
                            "l.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn7Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn8() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn8Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn8' de la tabla 'cuadratura_fin_de_mes' es DBNul"& _ 
                            "l.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn8Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn9() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn9Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn9' de la tabla 'cuadratura_fin_de_mes' es DBNul"& _ 
                            "l.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn9Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn10() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn10Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn10' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn10Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn11() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn11Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn11' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn11Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn12() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn12Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn12' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn12Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn13() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn13Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn13' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn13Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn14() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn14Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn14' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn14Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn15() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn15Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn15' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn15Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn16() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn16Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn16' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn16Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn17() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn17Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn17' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn17Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn18() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn18Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn18' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn18Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn19() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn19Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn19' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn19Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn20() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn20Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn20' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn20Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property logo() As Byte()
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.logoColumn),Byte())
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'logo' de la tabla 'cuadratura_fin_de_mes' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.logoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn21() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn21Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn21' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn21Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn22() As Integer
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn22Column),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn22' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn22Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn23() As Integer
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn23Column),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn23' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn23Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn24() As Integer
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn24Column),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn24' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn24Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn25() As Integer
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn25Column),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn25' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn25Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn26() As Integer
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn26Column),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn26' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn26Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn27() As Integer
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn27Column),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn27' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn27Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn28() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn28Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn28' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn28Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn29() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn29Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn29' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn29Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn30() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn30Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn30' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn30Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn31() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn31Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn31' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn31Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn32() As Integer
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn32Column),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn32' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn32Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn33() As Integer
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn33Column),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn33' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn33Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn34() As Integer
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn34Column),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn34' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn34Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn35() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn35Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn35' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn35Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn36() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn36Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn36' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn36Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DataColumn37() As String
            Get
                Try 
                    Return CType(Me(Me.tablecuadratura_fin_de_mes.DataColumn37Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DataColumn37' de la tabla 'cuadratura_fin_de_mes' es DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tablecuadratura_fin_de_mes.DataColumn37Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn1Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn1Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn1Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn1Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn2Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn2Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn2Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn2Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn3Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn3Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn3Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn3Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn4Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn4Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn4Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn4Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn5Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn5Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn5Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn5Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn6Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn6Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn6Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn6Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn7Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn7Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn7Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn7Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn8Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn8Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn8Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn8Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn9Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn9Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn9Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn9Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn10Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn10Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn10Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn10Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn11Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn11Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn11Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn11Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn12Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn12Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn12Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn12Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn13Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn13Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn13Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn13Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn14Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn14Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn14Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn14Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn15Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn15Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn15Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn15Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn16Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn16Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn16Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn16Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn17Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn17Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn17Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn17Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn18Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn18Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn18Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn18Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn19Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn19Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn19Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn19Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn20Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn20Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn20Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn20Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IslogoNull() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.logoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetlogoNull()
            Me(Me.tablecuadratura_fin_de_mes.logoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn21Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn21Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn21Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn21Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn22Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn22Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn22Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn22Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn23Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn23Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn23Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn23Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn24Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn24Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn24Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn24Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn25Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn25Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn25Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn25Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn26Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn26Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn26Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn26Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn27Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn27Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn27Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn27Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn28Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn28Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn28Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn28Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn29Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn29Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn29Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn29Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn30Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn30Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn30Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn30Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn31Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn31Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn31Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn31Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn32Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn32Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn32Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn32Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn33Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn33Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn33Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn33Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn34Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn34Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn34Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn34Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn35Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn35Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn35Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn35Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn36Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn36Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn36Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn36Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDataColumn37Null() As Boolean
            Return Me.IsNull(Me.tablecuadratura_fin_de_mes.DataColumn37Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDataColumn37Null()
            Me(Me.tablecuadratura_fin_de_mes.DataColumn37Column) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class cuadratura_fin_de_mesRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As cuadratura_fin_de_mesRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As cuadratura_fin_de_mesRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As cuadratura_fin_de_mesRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
